[tool.black]
line-length = 99
target-version = ['py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
src_paths = ["tremana", "test"]
include_trailing_comma = true
line_length = 99
force_single_line = true
remove_redundant_aliases = true

[tool.interrogate]
exclude = ["setup.py", "docs", "tests"]
ignore-init-module = true
fail-under = 90

[tool.coverage.run]
branch = true
include = [
  'tremana/*',
]
omit = [
  'setup.py',
  'tremana/__init__.py',
  'tests/*',
# comment the above line if you want to see if all tests did run
  ]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
  # Have to re-enable the standard pragma
  'pragma: no cover',

  # Don't complain about missing debug-only code:
  'def __repr__',
  'if self\.debug',

  # Don't complain if tests don't hit defensive assertion code:
  'raise AssertionError',
  'raise NotImplementedError',

  # Don't complain if non-runnable code isn't run:
  'if 0:',
  'if __name__ == .__main__.:',
]

[tool.mypy]
ignore_missing_imports = true
scripts_are_modules = true
show_error_codes = true
disallow_incomplete_defs = false
disallow_untyped_defs = false
disallow_untyped_decorators = false


[[tool.mypy.overrides]]
module = "tremana.*"
disallow_incomplete_defs = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
